name: cleanup-files
description: "Cleans up files on the local system to reduce disk pressure"

runs:
  using: composite
  steps:
    - run: |
        lsblk -f

        echo "removing github actions pre-installed files"
        echo "Current time: $(date +"%T")"

        sudo rm -rf /usr/share/dotnet
        lsblk -f
        echo "dotnet: Current time: $(date +"%T")"

        sudo rm -rf /usr/local/lib/android
        lsblk -f
        echo "android: Current time: $(date +"%T")"

        # Remove haskell
        sudo rm -rf /opt/ghc
        lsblk -f
        echo "haskell: Current time: $(date +"%T")"

        sudo docker system prune --all --force
        lsblk -f
        echo "docker prune: Current time: $(date +"%T")"

        sudo rm -rf /opt/hostedtoolcache/CodeQL
        lsblk -f
        echo "codeql: Current time: $(date +"%T")"


        echo "removing zarf sboms, packages, cache"
        sudo rm -rf zarf-sbom /tmp/zarf-*
        sudo env "PATH=$PATH" CI=true make delete-packages
        sudo build/zarf tools clear-cache

        lsblk -f
      shell: bash
