apiVersion: v1
kind: Service
metadata:
  name: zarf-connect-longhorn-ui
  labels:
    # Enables "zarf connect longhorn-ui"
    zarf.dev/connect-name: longhorn-ui    
  annotations:
    zarf.dev/connect-description: "Connect to the Longhorn User Interface"
spec:
  ports:
  - port: 80