kind: ZarfPackageConfig
metadata:
  name: appliance-demo-pod-info
  description: "Demo Zarf appliance mode with pod info"

local:
  manifestFolder: manifests
  
  images:
    - ghcr.io/stefanprodan/podinfo:6.0.0
