stages:
  - package

build:
  stage: package
  tags:
    - bigbang
    - privileged
    - packages
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_DRIVER: overlay2
  # only:
  #   variables: 
  #     - $CI_COMMIT_TAG
  image: docker:git
  before_script:
    - echo "$REGISTRY1_PASSWORD" | docker login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password-stdin
  script:
    - wget https://github.com/earthly/earthly/releases/download/v0.5.13/earthly-linux-amd64
    - mv earthly-linux-amd64 /usr/bin/earthly && chmod +x /usr/bin/earthly
    - pwd && ls -lah
