stages:
  - build
  - package
  - upload
  - release

# Templates
.package:
  stage: package
  needs:
    - job: compile
      artifacts: true
  tags:
    - bigbang
    - packages
  image: golang:1.16
    - curl -fL https://get.helm.sh/helm-v3.6.1-linux-amd64.tar.gz | tar xz && cp linux-amd64/helm /usr/local/bin/
    - ./build/zarf registry login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password "$REGISTRY1_PASSWORD"
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - build/
    expire_in: never

.artifact-upload:
  image: amazon/aws-cli
  stage: upload
  needs:
    - job: package
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - aws s3 cp build s3://zarf-public/$RELEASE_FOLDER/$CI_COMMIT_TAG --region us-gov-west-1 --recursive
  variables:
    RELEASE_FOLDER: "release"

.generate-release:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: artifact-upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf Appliance ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf Appliance Mode"
      --assets-link "{\"name\":\"zarf\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/$RELEASE_FOLDER/$CI_COMMIT_TAG/zarf\"}"
      --assets-link "{\"name\":\"zarf-mac-apple\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/$RELEASE_FOLDER/$CI_COMMIT_TAG/zarf-mac-apple\"}"
      --assets-link "{\"name\":\"zarf-mac-intel\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/$RELEASE_FOLDER/$CI_COMMIT_TAG/zarf-mac-intel\"}"
      --assets-link "{\"name\":\"zarf-init.tar.zst\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/$RELEASE_FOLDER/$CI_COMMIT_TAG/zarf-init.tar.zst\"}"
      --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/$RELEASE_FOLDER/$CI_COMMIT_TAG/zarf.sha256\"}"

# Jobs
compile:
  stage: build
  image: golang:1.16
  script:
    - make build-cli
  artifacts:
    paths:
      - build/

utility-cluster-package:
  extends: .package
  script:
    - make ci-release

appliance-cluster-package:
  extends: .package
  script:
    - make ci-release-appliance

utility-cluster-artifact-upload:
  extends: .artifact-upload
  needs:
    - job: utility-cluster-package
      artifacts: true
  variables:
    RELEASE_FOLDER: "release"

appliance-cluster-artifact-upload:
  extends: .artifact-upload
  needs:
    - job: appliance-cluster-package
      artifacts: true
  variables:
    RELEASE_FOLDER: "release-appliance"

utility-cluster-generate-release:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: utility-cluster-artifact-upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf Utility Cluster" 
        --assets-link "{\"name\":\"zarf\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf\"}" 
        --assets-link "{\"name\":\"zarf-mac-apple\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-mac-apple\"}" 
        --assets-link "{\"name\":\"zarf-mac-intel\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-mac-intel\"}" 
        --assets-link "{\"name\":\"zarf-init.tar.zst\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-init.tar.zst\"}" 
        --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf.sha256\"}"
        
appliance-cluster-generate-release:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: appliance-cluster-artifact-upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating an appliance release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf Appliance ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf package to initialize an appliance mode cluster.  https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/tree/master/examples/appliance" 
        --assets-link "{\"name\":\"zarf-init.tar.zst\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release-appliance/$CI_COMMIT_TAG/zarf-init.tar.zst\"}" 
        --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release-appliance/$CI_COMMIT_TAG/zarf.sha256\"}"