stages:
  - build
  - package
  - e2e
  - upload
  - release

.only-default: &only-default
  only:
    - master
    - merge_requests
    - tags  

compile:
  only: 
    - branches
    - merge_requests
    - tags
  stage: build
  image: golang:1.16
  script:
    - make build-cli
  artifacts:
    paths:
      - build/

package:
  <<: *only-default
  stage: package
  needs:
    - job: compile
      artifacts: true
  tags:
    - bigbang
    - packages
  image: golang:1.16
  before_script:
    - ./build/zarf tools registry login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password "$REGISTRY1_PASSWORD"
  script:
    - make ci-release
  after_script:
    - echo "PACKAGE_JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    reports:
      dotenv: job.env    
    paths:
      - build/

e2e:
  <<: *only-default
  stage: e2e
  needs:
    - job: package
      artifacts: true
  tags:
    - bigbang
    - packages      
  before_script:
    - yum install openssh-clients -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ZARF_PIPELINE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$ZARF_KNOWN_HOST" > ~/.ssh/known_hosts
    - ./build/zarf tools registry login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password "$REGISTRY1_PASSWORD"
  script:
    - ./e2e.sh
  resource_group: e2e
  artifacts:
    paths:
      - build/

artifact-upload:
  image: amazon/aws-cli
  stage: upload
  needs:
    - job: e2e
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - aws s3 cp build s3://zarf-public/release/$CI_COMMIT_TAG --region us-gov-west-1 --recursive

generate-release:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: artifact-upload
  script:
    - release-cli create --name "Zarf ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf K8s Airgap Buddy
      --assets-link "{\"name\":\"zarf\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf\"}"
      --assets-link "{\"name\":\"zarf-mac-apple\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-mac-apple\"}"
      --assets-link "{\"name\":\"zarf-mac-intel\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-mac-intel\"}"
      --assets-link "{\"name\":\"zarf-init.tar.zst\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-init.tar.zst\"}"
      --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf.sha256\"}"
