stages:
  - package
  - release

build:
  stage: package
  tags:
    - bigbang
    - privileged
    - packages
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_DRIVER: overlay2
    DOCKER_OPTS: "--mtu=1400"
  image: docker:git
  before_script:
    - ip a | grep mtu
    - docker network inspect bridge
    - echo "$REGISTRY1_PASSWORD" | docker login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password-stdin
    - wget https://github.com/earthly/earthly/releases/download/v0.5.13/earthly-linux-amd64
    - mv earthly-linux-amd64 /usr/bin/earthly && chmod +x /usr/bin/earthly
  # rules:
  #   - if: $CI_COMMIT_TAG    
  script:
    - earthly -s IB_USER="robot\$bb-dev-imagepullonly" -s IB_PASS="$REGISTRY1_PASSWORD" +test-ci
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - build/
    expire_in: never
    reports:
      dotenv: job.env

release-from-tag:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG                    
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf Utility Cluster" 
        --assets-link "{\"name\":\"zarf\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf\"}" 
        --assets-link "{\"name\":\"zarf-initialize.tar.zst\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf-initialize.tar.zst\"}" 
        --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf.sha256\"}"