stages:
  - build
  - package
  - upload
  - release

compile:
  stage: build
  image: golang:1.16
  script:
    - make build-cli
  artifacts:
    paths:
      - build/

package:
  stage: package
  needs:
    - job: compile
      artifacts: true
  tags:
    - bigbang
    - packages
  image: golang:1.16
  before_script:
    - curl -fL https://get.helm.sh/helm-v3.6.1-linux-amd64.tar.gz | tar xz && cp linux-amd64/helm /usr/local/bin/ 
    - ./build/zarf registry login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password "$REGISTRY1_PASSWORD" 
  rules:
    - if: $CI_COMMIT_TAG    
  script:
    - make ci-release
  artifacts:
    paths:
      - build/
    expire_in: never
    
artifact-upload:
  image: amazon/aws-cli
  stage: upload
  needs:
    - job: package
      artifacts: true  
  script:
    - aws s3 cp build s3://zarf-public/release/$CI_COMMIT_TAG --region us-gov-west-1 --recursive

generate-release:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: artifact-upload          
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf Utility Cluster" 
        --assets-link "{\"name\":\"zarf\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf\"}" 
        --assets-link "{\"name\":\"zarf-initialize.tar.zst\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-initialize.tar.zst\"}" 
        --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf.sha256\"}"