stages:
  - package

build:
  stage: package
  tags:
    - bigbang
    - privileged
    - packages
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_DRIVER: overlay2
  # only:
  #   variables: 
  #     - $CI_COMMIT_TAG
  image: docker:19.03.12
  before_script:
    - echo $REGISTRY1_USER
    - echo "$REGISTRY1_PASSWORD" | docker login registry1.dso.mil --username "robot$$bb-dev-imagepullonly" --password-stdin
  script:
    - docker info
    - docker pull registry1.dso.mil/ironbank/opensource/docker/registry-v2:2.7.1
