stages:
  - package
  - release

build:
  stage: package
  tags:
    - bigbang
    - packages
  image: registry1.dso.mil/ironbank/google/golang/golang-1.16
  before_script:
    - make build-cli
    - ./build/zarf registry login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password "$REGISTRY1_PASSWORD" 
  # rules:
  #   - if: $CI_COMMIT_TAG    
  script:
    - make release
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - build/
    expire_in: never
    reports:
      dotenv: job.env

release-from-tag:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG                    
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf Utility Cluster" 
        --assets-link "{\"name\":\"zarf\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf\"}" 
        --assets-link "{\"name\":\"zarf-initialize.tar.zst\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf-initialize.tar.zst\"}" 
        --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf.sha256\"}"