stages:
  - build
  - package
  - release

compile:
  stage: build
  image: golang:1.16
  script:
    - make build-cli
  artifacts:
    paths:
      - build/

package:
  stage: package
  needs:
    - job: compile
      artifacts: true
  tags:
    - bigbang
    - packages
  image: golang:1.16
  before_script:
    - curl -fL https://get.helm.sh/helm-v3.6.1-linux-amd64.tar.gz | tar xz && cp linux-amd64/helm /usr/local/bin/ 
    - ./build/zarf registry login registry1.dso.mil --username "robot\$bb-dev-imagepullonly" --password "$REGISTRY1_PASSWORD" 
  rules:
    - if: $CI_COMMIT_TAG    
  script:
    - make release
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - build/
    expire_in: never
    reports:
      dotenv: job.env

generate-release:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: package
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG                    
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf Utility Cluster" 
        --assets-link "{\"name\":\"zarf\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf\"}" 
        --assets-link "{\"name\":\"zarf-initialize.tar.zst\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf-initialize.tar.zst\"}" 
        --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/jobs/${JOB_ID}/artifacts/file/build/zarf.sha256\"}"