run:
  timeout: 5m
  skip-files:
    - cli/internal/message/logo.go  
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - lll
    - stylecheck
    - wrapcheck
    - wsl
issues:
  exclude-use-default: false
