# Ignore file for false positives from protobuf, see the following for more information:
#   https://github.com/anchore/grype/issues/558
ignore:
  # False positive from CPE confusion of NPM vs Rust Crates (https://github.com/anchore/grype/issues/931)
  - vulnerability: CVE-2017-18589

  # False positive from CPE confusion of an NPM package vs a website (https://github.com/anchore/grype/issues/446)
  - vulnerability: CVE-2002-1647

  # False positive from CPE confusion of svelte and svelte's extension
  - vulnerability: CVE-2021-29261

  # False positive from CPE confusion of a php vulnerability , https://nvd.nist.gov/vuln/detail/CVE-2018-25076
  - vulnerability: CVE-2018-25076

  # From rouille - The Zarf injector does not expose endpoints that use multipart form data
  - vulnerability: GHSA-mc8h-8q98-g5hr
