# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name:
  region: us-east-1
  version: "1.27"

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: "v1.21.0-eksbuild.1"
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

managedNodeGroups:
- instanceType: t3.small
  name: -ng
  minSize: 3
  maxSize: 6
  spot: true
