# https://taskfile.dev

version: "3"

tasks:
  compile:
    desc: Compile the app
    cmds:
      - make build-cli

  login:registry1:
    desc: Login to registry1.dso.mil
    vars:
      REGISTRY1_USERNAME: '{{ coalesce .REGISTRY1_USERNAME "<no value>" }}'
      REGISTRY1_PASSWORD: '{{ coalesce .REGISTRY1_PASSWORD "<no value>" }}'
    preconditions:
      - sh: test "{{.REGISTRY1_USERNAME}}" != "<no value>"
        msg: Required variable 'REGISTRY1_USERNAME' not set
      - sh: test "{{.REGISTRY1_PASSWORD}}" != "<no value>"
        msg: Required variable 'REGISTRY1_PASSWORD' not set
    cmds:
      - ./build/zarf-mac-intel tools registry login registry1.dso.mil --username {{.REGISTRY1_USERNAME}} --password {{.REGISTRY1_PASSWORD}}

  package:
    desc: Make the deploy package
    cmds:
      - make ci-release

  test:e2e:
    desc: Run E2E tests
    dir: test/e2e
    cmds:
      - go test ./... -v -timeout 1200s

  ssh:
    desc: SSH into the box
    cmds:
      - rm -f tmp.id_rsa
      - cat test/tf/public-ec2-instance/.test-data/Ec2KeyPair.json | jq -r .PrivateKey > tmp.id_rsa
      - chmod 0400 tmp.id_rsa
      - ssh -i ./tmp.id_rsa ubuntu@$(cat test/tf/public-ec2-instance/terraform.tfstate | jq -r .outputs.public_instance_ip.value)
