tmpdir = ""
log_level = ""
architecture = ""
no_log_file = false
no_progress = false

[connect]
name = ""
namespace = ""
resource_type = ""
local_port = ""
remote_port = ""
cli_only = false

[destroy]
remove_components = false

[init]
components = ""
storage_class = ""
secret = ""
nodeport = ""

[package.create]
zarf_cache = ""
output_directory = ""
skip_sbom = false
insecure = false

[package.create.set]
# example1 = "value 1"
# example2 = "value 2"

[package.deploy]
components = ""
insecure = false
shasum = ""
sget = ""

[package.deploy.set]
# example1 = "value 1"
# example2 = "value 2"

[package.inspect]
sbom = false

[package.remove]
components = ""

[prepare.set]
# example1 = "value 1"
# example2 = "value 2"
