[package.create.set]
# The image reference to use for the Zarf agent, defaults to a locally built image
agent_image_domain = 'ghcr.io/'
agent_image = 'defenseunicorns/zarf/agent'
agent_image_tag = 'local'

# Tag for the zarf injector binary to use
injector_version = '2024-05-03'
injector_amd64_shasum = 'e5a3d380bac4bf6c68ba18275d6a92bb002e86c116eb364f960d393fd2f44da8'
injector_arm64_shasum = '866b5b1911dd920618be55164c4f95abe05753932ac6d0f2270d26e569d797a2'

# The image reference to use for the registry that Zarf deploys into the cluster
registry_image_domain = ''
registry_image = 'library/registry'
registry_image_tag = '2.8.3'

# The image reference to use for the optional git-server Zarf deploys
gitea_image = 'gitea/gitea:1.21.5-rootless'
