domain: bigbang.dev

registryCredentials:
  registry: "###ZARF_REGISTRY###"
  username: "zarf-pull"
  password: "###ZARF_REGISTRY_AUTH_PULL###"

git:
  existingSecret: "private-git-server"

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

networkPolicies:
  enabled: true
  # When in prod use a real CIDR. Don't do this, it isn't secure. This is done here since it is a demo and the CIDR changes based on which Linux distro you are running on.
  controlPlaneCidr: "0.0.0.0/0"
  nodeCidr: "0.0.0.0/0"

istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
  gateways:
    public:
      tls:
        key: |
          The chart won't let this be left blank. If it is blank, a default cert is applied (the `*.bigbang.dev` one)
        cert: |
          The chart won't let this be left blank. If it is blank, a default cert is applied (the `*.bigbang.dev` one)
  values:
    gateways:
      public:
        selector:
          app: "public-ingressgateway"
        servers:
          - hosts:
              - "*.bigbang.dev"
            port:
              name: https
              number: 8443
              protocol: HTTPS
            tls:
              credentialName: public-cert-actual
              mode: SIMPLE
    kiali:
      dashboard:
        auth:
          strategy: "anonymous"

jaeger:
  enabled: false

clusterAuditor:
  enabled: false

gatekeeper:
  enabled: false

logging:
  enabled: false

eckoperator:
  enabled: false

fluentbit:
  enabled: false

monitoring:
  enabled: false

twistlock:
  enabled: false
