apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry
  namespace: kafka-operator
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.dso.mil": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "registry1.dso.mil": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "docker.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "registry-1.docker.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "ghcr.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        }
      }
    }
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry
  namespace: kafka-demo
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.dso.mil": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "registry1.dso.mil": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "docker.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "registry-1.docker.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "ghcr.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        }
      }
    }
