apiVersion: v1
kind: Namespace
metadata:
  name: kafka-operator
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: strimzi
  namespace: kafka-operator
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/strimzi-kafka-operator.tgz
  targetNamespace: kafka-operator
  valuesContent: |-
    imageRegistryOverride: registry1.dso.mil
    imageRepositoryOverride: ironbank/opensource/strimzi
    image:
      pullPolicy: Never
    watchNamespaces: 
      - kafka-demo