kind: ZarfPackageConfig
metadata:
  name: appliance-demo-doom
  description: "Demo Zarf appliance mode with doom game"

local:
  manifestFolder: manifests

  images:
    - registry.dso.mil/platform-one/big-bang/apps/product-tools/zarf/game:doom
