name: packages
description: "Create agent image, init package and example packages"

inputs:
  username:
    description: "Registry username"
    default: zarfdev
  password:
    description: "Registry password"
    required: true

runs:
  using: composite
  steps:
    - run: make build-cli-linux-amd
      shell: bash

    - uses: ./.github/actions/agent-image
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - run: make init-package build-examples ARCH=amd64 AGENT_IMAGE=${{inputs.username}}/agent:$GITHUB_SHA
      shell: bash
