name: packages
description: "Create agent image, init package and example packages"

runs:
  using: composite
  steps:
    - run: |
        make build-cli-linux-amd init-package build-examples ARCH=amd64 CLI_VERSION=${GITHUB_SHA:0:7}
      shell: bash
