name: packages
description: "Create agent image, init package and example packages"

runs:
  using: composite
  steps:
    - run: |
        make init-package build-examples ARCH=amd64
      shell: bash
