name: setup-go
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        role-to-assume: ${{ secrets.AWS_NIGHTLY_ROLE }}
        aws-region: us-east-1
        role-duration-seconds: 14400
