name: agent-image
description: "Create and push the Zarf Agent image"

inputs:
  username:
    description: "Docker Hub username"
    required: true
  password:
    description: "Docker Hub password"
    required: true

runs:
  using: composite
  steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - run: |
        cp build/zarf build/zarf-linux-amd64
        docker buildx build --push --platform linux/amd64 --tag zarfdev/agent:$GITHUB_SHA .
      shell: bash
