name: agent-image
description: "Create and push the Zarf Agent image"

inputs:
  tag:
    description: "Image tag"
    required: true
  architecture:
    description: "Image architecture"
    default: amd64

runs:
  using: composite
  steps:
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: dummy
        password: ${{ github.token }}

    - run: docker buildx build --push --platform linux/${{inputs.architecture}} --tag ghcr.io/defenseunicorns/zarf/${{inputs.tag}} .
      shell: bash
