name: debug-cluster
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - run: |
        echo "***** Getting pods *****"
        kubectl get pods -A -o yaml

        echo "***** Describing pods *****"
        kubectl describe pods -A

        echo "***** Getting nodes *****"
        kubectl describe nodes -A

        echo "***** describing nodes *****"
        kubectl describe nodes -A
      shell: bash
