apiVersion: v1
kind: Pod
metadata:
  name: data-injection
  namespace: demo
  labels:
    app: data-injection
spec:
  containers:
    - name: data-injection
      image: alpine:3.15
      command:
        [
          "/bin/sh",
          "-ec",
          "mkdir -p /test && while :; do ls -lah /test; sleep 5 ; done",
        ]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
