apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zarf-image-preloader
spec:
  selector:
    matchLabels:
      app: image-preloader
  template:
    metadata:
      labels:
        app: image-preloader
        zarf.dev/agent: ignore
    spec:
      imagePullSecrets:
        - name: private-registry
      priorityClassName: system-cluster-critical
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: sleep
          image: "###ZARF_REGISTRY###/library/registry:2.8.1"
          imagePullPolicy: IfNotPresent
          # Sleep for 6 hrs and then let the pod restart
          command: ["sleep", "21600"]
          resources:
            requests:
              cpu: "2m"
              memory: "2Mi"
            limits:
              cpu: "100m"
              memory: "24Mi"
