persistence:
  storageClass: "###ZARF_STORAGE_CLASS###"
  size: "###ZARF_VAR_REGISTRY_PVC_SIZE###"
  existingClaim: "###ZARF_VAR_REGISTRY_EXISTING_PVC###"

image:
  repository: "###ZARF_REGISTRY###/library/registry"

imagePullSecrets:
  - name: private-registry

secrets:
  htpasswd: "###ZARF_HTPASSWD###"
  configData:
    http:
      secret: "###ZARF_REGISTRY_SECRET###"

service:
  nodePort: "###ZARF_NODEPORT###"

resources:
  requests:
    cpu: "###ZARF_VAR_REGISTRY_CPU_REQ###"
    memory: "###ZARF_VAR_REGISTRY_MEM_REQ###"
  limits:
    cpu: "###ZARF_VAR_REGISTRY_CPU_LIMIT###"
    memory: "###ZARF_VAR_REGISTRY_MEM_LIMIT###"

fullnameOverride: "zarf-docker-registry"

podLabels:
  zarf.dev/agent: "ignore"
