persistence:
  enabled: true
  storageClass: "###ZARF_STORAGE_CLASS###"
  size: 20Gi
image:
  repository: "###ZARF_REGISTRY###/library/registry"
  tag: 2.8.1
imagePullSecrets:
  - name: private-registry
secrets:
  htpasswd: "###ZARF_HTPASSWD###"
  configData:
    http:
      secret: "###ZARF_REGISTRY_SECRET###"
service:
  type: NodePort
  nodePort: "###ZARF_NODEPORT###"
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "3"
    memory: "2Gi"
fullnameOverride: "zarf-docker-registry"
podLabels:
  zarf.dev/agent: "ignore"
