---
apiVersion: v1
kind: Namespace
metadata:
  name: registry

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kevin
  namespace: registry
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/docker-registry-1.10.1.tgz
  targetNamespace: registry
  valuesContent: |-
    persistence:
      enabled: true