---
apiVersion: v1
kind: Namespace
metadata:
  name: git

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: git
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/gitea-2.2.5.tgz
  targetNamespace: git
  valuesContent: |-
    dbType: "sqlite"
    persistence:
      storageClass: local-path
    gitea:
      cache:
        builtIn:
          enabled: false
