image: golang:1.16

stages:
  - test
  - build
  - release

format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test ./...

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/zarf
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - zarf
    expire_in: never
    reports:
      dotenv: job.env

release-from-tag:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  needs:
    - job: compile
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    - release-cli create --name "Zarf CLI ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "CLI for Zarf"
      --assets-link "{\"name\":\"zarf\",\"url\":\"https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/cli/-/jobs/${JOB_ID}/artifacts/raw/zarf\"}"
        