kind: ZarfPackageConfig
metadata:
  name: cli-test
  description: "Test package for zarf"
  uncompressed: true

remote:
  # helm template bigbang ./chart |  yq e '. | select(.kind == "GitRepository") | "- " + .spec.url + "@" + .spec.ref.tag' -
  # https://repo1.dso.mil/platform-one/big-bang/bigbang/-/tags/1.12.0
  repos:
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/cluster-auditor.git@0.3.0-bb.2
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/policy.git@3.4.0-bb.13
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git@1.8.4-bb.5
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git@1.8.4-bb.2
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/jaeger.git@2.21.4-bb.2
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/kiali.git@1.36.0-bb.1
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/eck-operator.git@1.6.0-bb.0
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/elasticsearch-kibana.git@0.1.16-bb.0
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/fluentbit.git@0.15.14-bb.1
    - https://repo1.dso.mil/platform-one/big-bang/apps/core/monitoring.git@11.0.0-bb.27
    - https://repo1.dso.mil/platform-one/big-bang/apps/security-tools/twistlock.git@0.0.6-bb.0

  images:
    - registry.dso.mil/platform-one/big-bang/apps/core/cluster-auditor/opa-collector:0.3.0-ib
    # - registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:1.3.0
    # - registry1.dso.mil/ironbank/elastic/elasticsearch/elasticsearch:7.9.2
    # - registry1.dso.mil/ironbank/elastic/kibana/kibana:7.9.2
    # - registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.7.0
    # - registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.7.4
    # - registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.8.0
    # - registry1.dso.mil/ironbank/fluxcd/source-controller:v0.8.1
    - registry1.dso.mil/ironbank/kiwigrid/k8s-sidecar:1.3.0
    # - registry1.dso.mil/ironbank/opensource/coreos/kube-state-metrics:v1.9.7
    # - registry1.dso.mil/ironbank/opensource/coreos/prometheus-config-reloader:v0.42.1
    # - registry1.dso.mil/ironbank/opensource/coreos/prometheus-operator:v0.42.1
    # - registry1.dso.mil/ironbank/opensource/fluent/fluent-bit:1.7.2
    # - registry1.dso.mil/ironbank/opensource/grafana/grafana:7.1.3-1
    # - registry1.dso.mil/ironbank/opensource/istio-1.7/proxyv2-1.7:1.7.7
    # - registry1.dso.mil/ironbank/opensource/istio/operator:1.7.3
    # - registry1.dso.mil/ironbank/opensource/istio/pilot:1.7.3
    # - registry1.dso.mil/ironbank/opensource/jaegertracing/all-in-one:1.19.2
    # - registry1.dso.mil/ironbank/opensource/jet/kube-webhook-certgen:v1.5.1
    # - registry1.dso.mil/ironbank/opensource/jimmidyson/configmap-reload:v0.4.0
    # - registry1.dso.mil/ironbank/opensource/kiali/kiali:v1.23.0
    # - registry1.dso.mil/ironbank/opensource/openpolicyagent/gatekeeper:v3.1.2
    # - registry1.dso.mil/ironbank/opensource/prometheus/alertmanager:v0.21.0
    # - registry1.dso.mil/ironbank/opensource/prometheus/node-exporter:v1.0.1
    # - registry1.dso.mil/ironbank/opensource/prometheus/prometheus:v2.22.0
    # - registry1.dso.mil/ironbank/twistlock/console/console:20.12.531    