---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/metallb-2.3.2.tgz
  targetNamespace: metallb-system
  valuesContent: |-
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.64.23-192.168.64.200
