apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: zarf
webhooks:
  - name: agent-hook.zarf.dev
    namespaceSelector:
      matchLabels:
        # Only operate on zarf-managed namespaces until the webhook can create secrets
        app.kubernetes.io/managed-by: "zarf"
      matchExpressions:
        # Ensure we don't mess with kube-sustem
        - key: name
          operator: NotIn
          values: ["kube-system"]
        # Allow zarf-managed namespaces to be ignore
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
    objectSelector:
      matchExpressions:
        # Always ignore specific resources if requested by annotation/label
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
    clientConfig:
      service:
        name: agent-hook
        namespace: zarf
        path: "/mutate/pods"
      caBundle: "###ZARF_AGENT_CA###"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
