domain: bigbang.dev

registryCredentials:
  registry: "registry1.dso.mil"
  username: "zarf-git-user"
  password: "${zarf_secret}"

git:
  existingSecret: "zarf-git-secret"

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

networkPolicies:
  enabled: true
  # When in prod use a real CIDR. Don't do this, it isn't secure. This is done here since it is a demo and the CIDR changes based on which Linux distro you are running on.
  controlPlaneCidr: "0.0.0.0/0"
  nodeCidr: "0.0.0.0/0"

istio:
  enabled: true
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__istio-controlplane.git
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        service:
          ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 9080
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 9443
              protocol: TCP
              targetPort: 8443
            - name: tls
              port: 15443
              protocol: TCP
              targetPort: 15443
  gateways:
    public:
      tls:
        credentialsName: "public-cert"
        mode: "SIMPLE"

  values:
    istiod:
      hpaSpec:
        maxReplicas: 1
        minReplicas: 1
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "500m"
          memory: "1Gi"
    kiali:
      dashboard:
        auth:
          strategy: "anonymous"

istiooperator:
  enabled: true
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__istio-operator.git
  values:
    operator:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"

jaeger:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__jaeger.git
  values:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
    jaeger:
      spec:
        allInOne:
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
        collector:
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
        ingester:
          # TODO: Remove this once the upstream bug is fixed (https://repo1.dso.mil/platform-one/big-bang/apps/core/jaeger/-/issues/15)
          image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-ingester:1.24.0

kiali:
  enabled: true
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__kiali.git
  values:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    cr:
      spec:
        deployment:
          resources:
            requests:
              cpu: "100m"
              memory: "368Mi"
            limits:
              cpu: "500m"
              memory: "368Mi"

clusterAuditor:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__cluster-auditor.git
  values:
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

gatekeeper:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__policy.git
  values:
    replicas: 1
    controllerManager:
      resources:
        requests:
          cpu: "175m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "2Gi"
    audit:
      resources:
        requests:
          cpu: "200m"
          memory: "768Mi"
        limits:
          cpu: "1.2"
          memory: "2Gi"
    violations:
      allowedDockerRegistries:
        parameters:
          excludedResources:
            # K3s kube-system stuff, better than excluding the whole namespace
            - "kube-system/coredns-.*"
            - "kube-system/local-path-provisioner-.*"
            - "kube-system/metrics-server-.*"
            - "kube-system/svclb-.*"
            - "kube-system/traefik-.*"
            # K3s needs these due to how it creates services of type "LoadBalancer"
            - "istio-system/lb-port-.*"
            - "istio-system/svclb-.*"
            # K3s needs this if you are doing K3s-specific "HelmRelease"-type CRDs
            - ".*/helm-install-.*"
            - ".*/helm"
            # TODO: Get Gitea in Iron Bank
            - "git/stuart-gitea-.*"
            - "git/gitea"
            - "git/init"
      hostNetworking:
        parameters:
          excludedResources:
            # K3s needs these due to how it creates services of type "LoadBalancer"
            - "istio-system/svclb-.*"
            - "istio-system/lb-port-.*"
      httpsOnly:
        parameters:
          excludedResources:
            # TODO: Fix these ingresses so they don't need to be excluded
            - "git/git-ingress"
            - "registry/registry-ingress"

logging:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__elasticsearch-kibana.git
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: "5Gi"
        resources:
          requests:
            cpu: "100m"
            memory: "3Gi"
          limits:
            cpu: "500m"
            memory: "3Gi"
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: "100m"
            memory: "3Gi"
          limits:
            cpu: "500m"
            memory: "3Gi"
    kibana:
      count: 1
      resources:
        requests:
          memory: "1Gi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "500m"

eckoperator:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__eck-operator.git

fluentbit:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__fluentbit.git
  values:
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"

monitoring:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__monitoring.git
  values:
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
    prometheusOperator:
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
    grafana:
      sidecar:
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "500m"
            memory: "100Mi"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
    kube-state-metrics:
      resources:
        requests:
          cpu: "10m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
    prometheus-node-exporter:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"

twistlock:
  enabled: false
  git:
    repo: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__security-tools__twistlock.git
  values:
    console:
      persistence:
        size: 5Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

addons:
  argocd:
    enabled: false
  authservice:
    enabled: false
  gitlab:
    enabled: false
  gitlabRunner:
    enabled: false
  anchore:
    enabled: false
  sonarqube:
    enabled: false
  minioOperator:
    enabled: false
  minio:
    enabled: false
  mattermostoperator:
    enabled: false
  mattermost:
    enabled: false
  nexus:
    enabled: false
  velero:
    enabled: false
  keycloak:
    enabled: false
