# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  region: us-east-1
  version: "1.21"
managedNodeGroups:
- instanceType: t3.small
  minSize: 3
  maxSize: 6
  spot: true