apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-data
spec:
  storageClassName: "###ZARF_VAR_KIWIX_STORAGE_CLASS###"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
