apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "acid-zarf-test"
  namespace: "postgres-operator"
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 2
  volume:
    size: "2Gi"
  users:
    zarf: []
  databases:
    zarf: zarf
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 1Gi
