---
apiVersion: v1
kind: Namespace
metadata:
  name: registry

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kevin
  namespace: yam
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/docker-registry-1.10.1.tgz
  targetNamespace: registry
  valuesContent: |-
    persistence:
      enabled: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: registry
  namespace: registry
spec:
  entryPoints:
    - registry
  routes:
  - match: HostSNI(`*`)
    kind: Rule
    services:
      - name: kevin-docker-registry
        port: 5000
