---
apiVersion: v1
kind: Namespace
metadata:
  name: git
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-ingress
  namespace: git
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 3000

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: git
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/gitea-2.2.5.tgz
  targetNamespace: git
  valuesContent: |-
    persistence:
      storageClass: local-path
    image:
      pullPolicy: Never
    gitea:
      admin:
        username: "bigbang"
        password: "change_me"
        email: "bigbang@localhost"
      cache:
        builtIn:
          enabled: false
      config:
        APP_NAME: "Big Bang Utility Cluster"
        server:
          DISABLE_SSH: true
        database: 
          DB_TYPE: sqlite3
          # Note that the init script checks to see if the IP & port of the database service is accessible, so make sure you set those to something that resolves as successful (since sqlite uses files on disk setting the port & ip won't affect the running of gitea).
          HOST: google.com:80
        service:
          DISABLE_REGISTRATION: true
        repository:
          ENABLE_PUSH_CREATE_USER: true
          FORCE_PRIVATE: true

      database:
        builtIn:
          postgresql:
            enabled: false
