# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
# name: CHANGE_ME_MUST_BE_UNIQUE  
  region: us-west-1
  version: "1.21"
managedNodeGroups:
- instanceType: t3.small
# name: CHANGE_ME_MUST_BE_UNIQUE
  minSize: 3
  maxSize: 6
  spot: true