# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ###ZARF_VAR_EKS_CLUSTER_NAME###
  region: ###ZARF_VAR_EKS_CLUSTER_REGION###
  version: "###ZARF_VAR_EKS_CLUSTER_VERSION###"
  tags:
    PermissionsBoundary: "zarf_dev_base_policy"

iam:
  withOIDC: true
  serviceRolePermissionsBoundary: "arn:aws:iam::173911864621:policy/zarf_dev_base_policy"

addons:
  - name: aws-ebs-csi-driver
    version: "###ZARF_VAR_EBS_DRIVER_VERSION###"
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    permissionsBoundary: "arn:aws:iam::173911864621:policy/zarf_dev_base_policy"
    tags:
      PermissionsBoundary: "zarf_dev_base_policy"

  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    permissionsBoundary: "arn:aws:iam::173911864621:policy/zarf_dev_base_policy"
    tags:
      PermissionsBoundary: "zarf_dev_base_policy"

managedNodeGroups:
- instanceType: ###ZARF_VAR_EKS_INSTANCE_TYPE###
  name: ###ZARF_VAR_EKS_CLUSTER_NAME###-ng
  minSize: 3
  maxSize: 6
  spot: true
  tags:
    PermissionsBoundary: "zarf_dev_base_policy"
  iam:
    instanceRolePermissionsBoundary: "arn:aws:iam::173911864621:policy/zarf_dev_base_policy"
