name: setup-go
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - name: "Dependency: Install Golang"
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: "Setup caching"
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/AppData/Local/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
