name: setup-go
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: 1.19.x
        cache: true
