---
apiVersion: v1
kind: Namespace
metadata:
  name: git

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: stuart
  namespace: yam
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/gitea-2.2.5.tgz
  targetNamespace: git

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: git
  namespace: git
spec:
  entryPoints:
    - git
  routes:
  - match: HostSNI(`*`)
    kind: Rule
    services:
      - name: stuart-git-server
        port: 9696