apiVersion: v1
kind: Pod
metadata:
  name: injector
  namespace: zarf
  labels:
    app: docker-registry
    release: zarf-docker-registry
spec:
  containers:
    - name: injector
      # image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.21.2-eksbuild.2
      # image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/coredns:v1.8.4-eksbuild.1
      image: rancher/local-path-provisioner:v0.0.19
      workingDir: /payload
      command: ["/zarf-bin/init.sh"]
      env:
        - name: SHA256_BUSYBOX
          value: 6a04784d38e8ced6432e683edb07015172acf57bf658d0653b1dc51c43b55643
        - name: SHA256_ZARF
          value: 707fbce6061aa8fdb378c2455e35d29922464c9cfc914ac9e7ed7ea0e9a601c0
        - name: SHA256_IMAGES
          value: 4cc08af8e749ba6fdbc0123847c039ec92c54ed147fc45f7ac6ab505fa44a70e
        - name: USER
          value: root
      volumeMounts:
        - name: payload
          mountPath: /payload
        - name: bin-volume
          mountPath: /zarf-bin/
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
  volumes:
    - name: payload
      emptyDir: {}
    - name: bin-volume
      configMap:
        name: injector-binaries
        defaultMode: 0777
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    zarf.dev/connect-name: seed-registry
  name: zarf-seed-registry
  namespace: zarf
spec:
  ports:
    - port: 25000
      protocol: TCP
  selector:
    app: docker-registry
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: zarf-docker-registry
    meta.helm.sh/release-namespace: zarf
  labels:
    app: docker-registry
    app.kubernetes.io/managed-by: Helm
  name: zarf-docker-registry
  namespace: zarf
spec:
  ports:
    - name: http-5000
      nodePort: 31999
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: docker-registry
    release: zarf-docker-registry
  type: NodePort
