apiVersion: v1
kind: Pod
metadata:
  name: injector
  namespace: zarf
  labels:
    app: zarf-injector
spec:
  containers:
    - name: injector
      image: rancher/local-path-provisioner:v0.0.19
      workingDir: /payload
      command: ["/zarf-bin/init.sh"]
      env:
        - name: SHA256_BUSYBOX
          value: 6a04784d38e8ced6432e683edb07015172acf57bf658d0653b1dc51c43b55643
        - name: SHA256_ZARF
          value: 1d196f71fdb3b0844f2d3676c42599b6c2eecc00904eecfa5716ea00cbab20df
        - name: SHA256_IMAGES
          value: 4cc08af8e749ba6fdbc0123847c039ec92c54ed147fc45f7ac6ab505fa44a70e
        - name: USER
          value: root
      volumeMounts:
        - name: payload
          mountPath: /payload
        - name: bin-volume
          mountPath: /zarf-bin/
      resources:
        requests:
          cpu: ".5"
          memory: "64Mi"
        limits:
          cpu: "1"
          memory: "256Mi"
  volumes:
    - name: payload
      emptyDir: {}
    - name: bin-volume
      configMap:
        name: injector-binaries
        defaultMode: 0777
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: zarf-injector
  namespace: zarf
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 31995
      protocol: TCP
  selector:
    app: zarf-injector
