apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-configmap
  namespace: zarf
data:
  templateme.properties: |
    zebra=###ZARF_VAR_DEPLOY_ZEBRA###
    leopard=###ZARF_VAR_DEPLOY_LEOPARD###
    cow=moo
