persistence:
  enabled: true
  storageClass: local-path
image:
  repository: "registry1.dso.mil/ironbank/opensource/docker/registry-v2"
imagePullSecrets:
  - name: zarf-registry
secrets:
  htpasswd: "###ZARF_HTPASSWD###"
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "2Gi"
