apiVersion: v1
kind: Namespace
metadata:
  name: pepr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
subjects:
  - kind: ServiceAccount
    name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
    namespace: pepr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-api-token
  namespace: pepr-system
type: Opaque
data:
  value: >-
    YWRhZjFmYTc1OTMyZjgyOTAyMmVjZWFhOTVlZTk0NDUwNGYxNmQ2NDEzMjg2OTNkOTE2MWJhMDZlZTEyMmJhYQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-tls
  namespace: pepr-system
type: kubernetes.io/tls
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDd3pDQ0FhdWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBQU1CNFhEVEl6TVRBeU1ESXlNREF4DQpNRm9YRFRJME1UQXlNREl5TURBeE1Gb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DDQpnZ0VCQUxZUnpkQ2RNUWx4SXFNR29zcUIvelNqa0x0elMvM1JxQkQ3K0ljRlZLZ3BjcWxtNW4wTU1qT2xPZTlRDQpsbW9ucnBFaFhzQXFxNmp0RmtsT1hvdGhGNzRjcVo3aFJhMnVWcVpZUXVhRktacFdDV0NOQi9MeWhjSHdnc2ZkDQpGdGxiOVJxT2dGWjBoNTEvY2tuQzd1cWFrZ1VEWElXd1FnbFQrdWZTNmxMTVN3M0g1TlY4Kzc2amVaQlR3alN3DQpTR0tESjBkUVRRbHNOTHZ1WmtMTFFDUlViTzBycUYveWFtclVxdk1YcmN5Y2Jjenc4bG14aElCWllJVUdFRk1rDQpVaFR4RXZOLzlyRHFvQUJZcitqT0FNV1IwZGtNNTJLbVlPc3FqaDFWQkY1T0Y4SE9TRzc3a2dsTGlJZmVnQnk0DQphUURhZ05PMGVCSmtzNEhoY29XOXRZSW5YNTBDQXdFQUFhTklNRVl3UkFZRFZSMFJCRDB3TzRJNWNHVndjaTFqDQpZalUyT1RObFppMWtNVE5qTFRWbVpURXRZalZoWkMxak9EY3dabVE1TVRGaU0ySXVjR1Z3Y2kxemVYTjBaVzB1DQpjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCVkhGUFdDaTk3UG0rN2xSMnZvN1pNZy9vbXhPa055ankzDQpSSk5vVVF4VU9QL2MzcGg1T0ZzbHFHcmZxWVhHQnVqNlAvKzN5UXYwa21TaGNBbVNEVmpxK0Z1S05UUGZSSFRFDQp2RXpncWdCeWFqeFlhRHNPdy9sUmNWOEllL3lQcVkvbU56T3NTcjlsLys2T3REYTBKT0VDMllrQjQzWU1kR0hCDQpycXFFQjdVbEV4TTFmRU9OcXV4WHA0KytBVVZSbERpT3ZZbzNGM0w3QXIzZFJjRVc5Q0xFdGRCaERqSFFldU1UDQppQTZSUHRXL29CSEpPU3dsMUZidlVBTWY1cnROK3d2M0xDWVIxVjd1ZEV5cy9OTW9yUnl4OWRqTzlLL1FpcmlEDQpqVjB4cUIzTzg4RVhlYTZtbmRsYWc4ck9pdmVBUEpuOEtlc1ZHM3p6dkpHNDJYL2liRlJsDQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRXBBSUJBQUtDQVFFQXRoSE4wSjB4Q1hFaW93YWl5b0gvTktPUXUzTkwvZEdvRVB2NGh3VlVxQ2x5cVdibQ0KZlF3eU02VTU3MUNXYWlldWtTRmV3Q3FycU8wV1NVNWVpMkVYdmh5cG51RkZyYTVXcGxoQzVvVXBtbFlKWUkwSA0KOHZLRndmQ0N4OTBXMlZ2MUdvNkFWblNIblg5eVNjTHU2cHFTQlFOY2hiQkNDVlA2NTlMcVVzeExEY2ZrMVh6Nw0KdnFONWtGUENOTEJJWW9NblIxQk5DV3cwdSs1bVFzdEFKRlJzN1N1b1gvSnFhdFNxOHhldHpKeHR6UER5V2JHRQ0KZ0ZsZ2hRWVFVeVJTRlBFUzgzLzJzT3FnQUZpdjZNNEF4WkhSMlF6bllxWmc2eXFPSFZVRVhrNFh3YzVJYnZ1Uw0KQ1V1SWg5NkFITGhwQU5xQTA3UjRFbVN6Z2VGeWhiMjFnaWRmblFJREFRQUJBb0lCQURrSDFhalpmRUZCWTRDZQ0KZFFLcStyWlIzK1dmcFhlUm95d0N5V1A5MnZrNzFuTlN6TEx4elkzWTNROWw5bCsxSTF6Smo2VHhHTWsyenFyUw0KdGhIQnJZNjY2clRlU3BXdlRPd1pMSWVKd2JEYTcyQURmVEJ3SUU3U0dCMGoxMkxwaDVxMGRXWGZaWldEbE5pZg0KQzNpSVIySHpuaGt3VDFjZHE3UFBJT0FqcHdUZkJtR0pycGx6WVV1OFJpM1A0am5ZYXY3dFdGRFhGTXNzYWE3cA0KWjd1UEdUbEpWQkVOb0VrSUd1NXhNNlRFeDFhV3UvSG45eGk1NXg0RVNMeElYcm9hY3E4Rzhmci9DdHhmeUxJbw0KcHZOMDdDUEIxc1RrZ1hidVR3UUU5T3VvRytEbXBIK1E4dU5lZ1lOK2pEL2lpUFp3TnZMejJpbmRKUzNidlFQRw0Kam0xMkg0OENnWUVBK1Bka3R6ZnJkWEV6R0FtMkpHblpmaWdoZHJrZ1o2dHVpc1N2M2JDbmY0ZVNXTkhQN1R2Tw0KV0FDNXpmQWVLN0RtM3Z4N3YwWWlHWFhjcGwveStWdFh3RTY4Y0ZUd2ViVjNRQVhIdE95TWg4d0RnejFvWGpqTw0KM0hGczIrMlhTVm9WbTVjZDhnQ2d2OVRjSjVhd0lteWM2dFJwZWJtbWlQbG52dWFHc3N0a1ViY0NnWUVBdXphWA0KTnlBRXZtcWQ0Q0g4TVFHZ2tMNTFMNi9yd2cvMFU3M0VnZHZ6RFMzbUhLb3FlblQ1RVlCS20wU1NtOVI0YnNDTw0Kb1BMTUxVbzk2WVFLeTBRK1QwMUU5S3JqMWVDeThqOWdaTi9tVXVwSnVkdTg1S0dXbGlPTWcyUnBYdGFIQ0EvbA0KYlF6MVVra3lURVdzeUNLVkg3QVZRQ2duYjJCVDU3MzQ3N0k4Q1VzQ2dZRUEyaWxQSkEzb1VoMUR2SWltQnZxSw0KRHpaelBHbTByNk5WVmx4TUQyTkJJMHRWUG1kOFlGSEwydW1uNTRIRnJsdHhzMnhqczVSdFJRbzJzOFBZVWhGcw0KcjZOUEZOQVplVTArbGVkNnZGdWNPVkxZc1NRYVZKWkxEbmlGLzZJT3M4UXdzd3FVdnY4MTNXTlZGNHZBQkNwUQ0KeHFZalZ2c0xwM09GS1k4djhYU3hEN2tDZ1lCeEI3U2tnNkJabHVWYXZTb1dMSFZVN3FpeDhmVFZaZXlONHJVUg0KOGtuOFd3bmpwSm1nOVo2ckFsb0pCSTIvcDdoT3BkTjNPU0FzOS9ZSlZyOXRtZlpFeXRJbkprWUlpM0YrOE9TeQ0KQXJ4OHN4ZHdMMHNNZnNMOFF0cERPZ3lrUmNHaERIZm9MenF1UTZNcWlhYVg3c2s2S0lXc0JwSkluRkFNU3BaUg0Kb2JxOW9RS0JnUUMwN3BPaVZCbFZwMTE5MDBWUXhJNFBXQjRUSVdtQk5JS1ZxRjNNZ1NtYVN1SFN6SlNZUTU4dA0KRmNEMFBZNDcvYlpHL2c2UTgyVWU2dHRRRW02T3JWZTNDWTFIOUV0YXprQlNJYWQ0ckRXQzNsWlp3bkdDbTN0ZQ0KdlhrcmpzOXg2UFlabzYrZm9DdlJtb3VQNXdsaDcxTXgvVGo5TzNzMTNqU242RFBVQWUrWVBRPT0NCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tDQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
  labels:
    app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  template:
    metadata:
      labels:
        app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
      containers:
        - name: server
          image: ghcr.io/defenseunicorns/pepr/controller:v0.14.2
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - 37665cd867b3afa9f23bc97c6e057d018325411a98e6d5e618a285b1ff75eb8a
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          env:
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: api-token
              mountPath: /app/api-token
              readOnly: true
            - name: module
              mountPath: /app/load
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-tls
        - name: api-token
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-api-token
        - name: module
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-module
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
spec:
  selector:
    app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-watcher
  namespace: pepr-system
spec:
  selector:
    app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-watcher
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-module
  namespace: pepr-system
type: Opaque
data:
  module-37665cd867b3afa9f23bc97c6e057d018325411a98e6d5e618a285b1ff75eb8a.js.gz: >-
    H4sIAAAAAAAAE61WXW/bNhR9769guSKRBoq1l2VLZShekG5Ft36haVFggYdQ0pXNWiY1kornqfrvu6TsxFuTrQ97iCKRl/fjnHMvfS0MWWSv849QOF5CJRW8MboB4zaTa9wrs0gxHWenC/xPlVgBZd21qFtINSu0quS8NSKvIX046uNwJM8M/N5KAxFtoDF0WK2zzp9OKfwhVk0NyRryhdZLyq7BWKlVSkd8xMeUlWALIxsX1ihbwmatTWnTy8Edo8sTi89G17LYJKDmmLP/xs1kpcu29l8WitZIt6EzNljYtFO6xPin2fgEA41oz/yR9L602laWKS3y4++eHEGVlOOjIjmuYJzkx6JMipPvR1X5ZDzOj3LKtPrRGG1SKudKG4wv6rXY2Ofha4hgG1FgEpczVoscav/W92yoFHOjy6MyseDahqb+nRR1ax0gAVCDAxKqK+GaHByQ/e3CgNjfTpLlkU2EmZPDBBfydv6DBYMQp6NDrLiEBlQJqpAekFA//Q1R/5Z/Q/s+ECXupG+VKVgTwc9FI3JZI7LRfcD9jb8zYqXfJlszUtw4IE4Tu9Br4v+2py1BrpdkLd2C/CpMRRC1pZgDwtDUerMC5SynbB9Q+ifa0VkfM5lRB9bdZtJ9WIBKl322miwjwQW/AMTLxfy5PQ+4la/N+6b0LxEuqlc7t9HgNOYfMJEXni8EY8gkGTJJpKo0GrxsHR6PVHbaIU9EZ4q/FWsGzDCbPRxPnNl0JhNO55HmGEmER+w3R30hXLHA7b2d3h+A7OeL1694I4yFyMSDXeTizi0MYuWZCHqLrn4SsobSIxmMiVsAsaHIW5cpedS5/iruKzzhk8Q0KwJTPlQC5bleNVp5aKfTy1nsuMWaWptlGX0aTKSa04MDRPCFnnNfeHT1DgMVu3M+APec9ERago1ncLHebEnD01cxA35j/mHL9ZRfumk4N8NXiQ+dB7GWz0CBEV5BmATw+c3ndMghCPv+JBbCElEjw+UG30sidvJCFeJcQLoJYkGk4+SVdttFTJMIpRFBw6/iNLoj4U+f7lrNuv7O8i6HdGZZt43u5bUdN5INGKf0bauUx5d9Xnu6XzlbC+metsMH6lgrHInjY5whFSprBU4Ewr13NgSO43jiSXw4mu4JLMudFlHQl3UGI8tqE6Ftum/z2TaOdmE3qiBVqwqfAanCvdAJnxZpo/EonnhtQTa0DjM76XuDaMQE/+XExqihpVTlbSPu9RzE/Bm4SO303qD3wDYMWh9GLLmV/Bzj7ebDIHpy+KhT/SGRityMCL8G/aHvgn+U1cS+K3zWduhQs9+hbr8JbcyKzN3BsR6kOynuEa/boxBbqNj1Fr1oiwKghJKyu/2i16yImfkP6hyy7JH+d5zPmqbGib2TyVaF6naQpoCXQ9gJz72oqLAOu6UYbvgv5aYNY/V/oKcvowqv8xqgOVPl+UKoOVwEDPFmulFji7LpMEJrVBiP+BtmJZE3nZ3ipfpOrkC3LtJMfT2GozhGp+3WKXrxB3L+Bi+7l+HnQ1Szy9Usnjx4/PgrYnWLtb8UTYNpvX/7IgtX7Zf8LOAfLV+J5sFfHWV5yGMJAAA=
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: peprstores.pepr.dev
spec:
  group: pepr.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: object
              additionalProperties:
                type: string
  scope: Namespaced
  names:
    plural: peprstores
    singular: peprstore
    kind: PeprStore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-store
  namespace: pepr-system
rules:
  - apiGroups:
      - pepr.dev/*
    resources:
      - peprstores
    resourceNames:
      - ''
    verbs:
      - create
      - get
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-store
  namespace: pepr-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-store
subjects:
  - kind: ServiceAccount
    name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-store
    namespace: pepr-system
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
webhooks:
  - name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b.pepr.dev
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlNekV3TWpBeU1qQXdNVEJhRncweU5ERXdNakF5TWpBd01UQmFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQ2JGVlNhMVFFRmdZNUNpenk0dHVrDQpSSzgrbndPK2Mvbm9ySmk2S3E0cTlPMnhLZGNCcXBHWjFaeENjd3ovT3dqM1RDSkUwT0tJam9ZVUVFQ3hmS2sxDQpHWjI0MGFxQjFhY1FUcWxRQ0FQdHBlZmJSTDNtU1FsT05wQ044cnpDRGJpVmR5OGV0dXlPcVptd3B6NEo1MHZPDQpjSUxtekpvREt1ZURreHNrb1ZqUkZveFBtLzQ5anE4dTBkRG1waXFlQnZWY1lRRm1lOEJ4cU01cjhPZy8vdXZ6DQpCZFk4djh4cEN2SjY1QllUa3E0WkJJVFhtR1VpbkxrZnJNZTkwT2k2RUpYbURheWl1dVFlNk1tVFdsVFdUWEh4DQoxKzBjSzl5NkgrbnVvYUV0cFA1STNCNklNLyttWlZObGN0ZGZvZUhaZEt4TDBtWFVqYmhIeTBySGRmMFpJTWtyDQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQWVoUFhlK0t5N2VpYVRUUXdrTyt5eE9qeC9XVXl0b3RVMXh2d3crZFhIR2c5VmFmdGt6aDM2DQpjMjJmZjNQMHBlNG1zdWdlNkdOY3NQcWhBc3lXYk1helRDUUxoYnB4UCtQQ1Zka1BhYlJZY0VFbXFXQkJrZC9IDQpJYmlEVXk5Y1pFYnE1b0Y5QmlDNTEvdWJLcWs3cU1IS2ZKTDd5MXJzVUNEWlJxWnhRVmVTT3VHZmVpOGp6VGIvDQp5MFNEeXJZdDdHS3p2YnVqb1UwdHV2QmNVb2Y1bEZJdTg2TDBWSnhuY3JtMUljekl5ZVg0UGNMWEU2LzNLR1IzDQo0a0dldGxiZ1hieW5JQ1JjcWEyeWloS0JXL2d4Y0gyeXdVWVhhRjdYa1FZSlpIMjBvamptNFBvWnlsM05xZVJqDQphM25WK1Qyd0Vrd2F2QkdROVROVnE1VWt6dHVlODVFUA0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
        namespace: pepr-system
        path: >-
          /mutate/adaf1fa75932f829022eceaa95ee944504f16d641328693d9161ba06ee122baa
    failurePolicy: Ignore
    matchPolicy: Equivalent
    timeoutSeconds: 10
    namespaceSelector:
      matchExpressions:
        - key: pepr.dev
          operator: NotIn
          values:
            - ignore
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    objectSelector:
      matchExpressions:
        - key: pepr.dev
          operator: NotIn
          values:
            - ignore
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - secrets
    sideEffects: None
