apiVersion: v1
kind: Namespace
metadata:
  name: pepr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
subjects:
  - kind: ServiceAccount
    name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
    namespace: pepr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-api-token
  namespace: pepr-system
type: Opaque
data:
  value: >-
    YzhhOWY5MjFhZGE4NzVkMTE2NmUxM2I3ODc1YzI5Mjk5MTRjOTYyNDNjYzIwNGU4MDE3ZjM4M2M3YmNiMmUzYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-tls
  namespace: pepr-system
type: kubernetes.io/tls
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDd3pDQ0FhdWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBQU1CNFhEVEl6TURnek1ERTJNVFExDQpORm9YRFRJME1EZ3pNREUyTVRRMU5Gb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DDQpnZ0VCQUs3NnlhOUExNkd1VjhZQ0o3UkliNWx5cHBPYkNKSlNNKzRocWMyM3o0NlUzbzgwc3ZpOGZjSnhmWFlmDQpNZk5xVklCR2tNSFMyd2VPVUxNM0kxOEpEbU0xTyswT09ZeFZYMEtpT3FTeFdJYVRvTU5BSXRDWEd6RGM2NklGDQp4L2VNam5IK2cyNnA2dG9FRCtVN3VJU2xNN2UwOWhobjluUlFuUG5rMEhhK3hDVUNhaUhnNGU2Z3R4SERjZXVBDQpSd0dZNzZGNmdXeDFWMTBGWDlsSjVvZjEyR3cxZ1pQSnJ0T2ozcTM2YzZLY2xNTk53UmVOaGlZMDk4aTA1VXFlDQp5TSthaWZyWWJzdW9MNUJVN0pHYWR5ek9abExGMU5UZFZtMVlqR3o4L3VjQlZKVHZDYU1oYVhod2svTzEza1RuDQp6Z2VmZi9lQkFvUkJFR2pjblZUZEJWTTMvRzBDQXdFQUFhTklNRVl3UkFZRFZSMFJCRDB3TzRJNWNHVndjaTFqDQpZalUyT1RObFppMWtNVE5qTFRWbVpURXRZalZoWkMxak9EY3dabVE1TVRGaU0ySXVjR1Z3Y2kxemVYTjBaVzB1DQpjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDT1RTRmJTa3padWxHTmJ3NWhIRHRFMDlUYTVGR0NCa2ZpDQppYkpxZ2NCRkdnTWw0YTIrZy96eDF4N2sreWRZK3BDN0RmV1JuQUNxOVpFNWpLMGNqZys2VlRCWHllc3BWUUc1DQpPV1R6eldXOGVrSFR0aUtXUVpJQmxSQUg0dXpqZ3cyUERjVXhIWEFrb2pyK3FWTW9XRWZuK3pmU0ZzeEpOdU9PDQpjV1hWRkIyRXAxcXhVVTg5aHVma0pSWmNLbFJQc0RzRnNxdHJVcERiSlkrYmExMEZIbVVmeVZZa3hZTjR5Y2R6DQpVMnVWdUJ0ZTJndVZ1d3IwRmExWHdUWXRhQlZjSEdjT01lTmJrSWxvT2M4RzRVZWVOS1Rzd1lKbk91dklwOTV0DQp4N2hBQVlvaHZId3E2SHBsZ2wxbnh5S0F5WUxUb28yUElFbE0zYjU4OXV5cm4zMHhTdWdODQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQXJ2ckpyMERYb2E1WHhnSW50RWh2bVhLbWs1c0lrbEl6N2lHcHpiZlBqcFRlanpTeQ0KK0x4OXduRjlkaDh4ODJwVWdFYVF3ZExiQjQ1UXN6Y2pYd2tPWXpVNzdRNDVqRlZmUXFJNnBMRllocE9ndzBBaQ0KMEpjYk1OenJvZ1hIOTR5T2NmNkRicW5xMmdRUDVUdTRoS1V6dDdUMkdHZjJkRkNjK2VUUWRyN0VKUUpxSWVEaA0KN3FDM0VjTng2NEJIQVpqdm9YcUJiSFZYWFFWZjJVbm1oL1hZYkRXQms4bXUwNlBlcmZwem9weVV3MDNCRjQyRw0KSmpUM3lMVGxTcDdJejVxSit0aHV5Nmd2a0ZUc2tacDNMTTVtVXNYVTFOMVdiVmlNYlB6KzV3RlVsTzhKb3lGcA0KZUhDVDg3WGVST2ZPQjU5Lzk0RUNoRUVRYU55ZFZOMEZVemY4YlFJREFRQUJBb0lCQUV4cjdkQWtBc2x6aXBSSg0KZHF2UGd5WkNvNndONXdWNDc0Tk9vb25kZ01JbUZMbjQ2ejJsblV0aUk4aUdRVnV0a2ZCZ1lYSzFzOEd1RDJMbQ0KYndWZndDL21IU0VndUZPcEthekJpOWxJTjRDM1UxeFRVNkZFamJTZW1DOHdWVEN4Njdpdnp4bHpEc1pmUmMzNQ0KY2xKRWtMem9SUjlOc0o4R1lqam1EWUgvT1UxcjhPMUd3YlBzcG1lbEUzelNhRVYxNmkyTlU0Z2MyVXhpMEZpYw0KVnBQU0t1ekpoYUVmVWJIR216aXRzUEg5eXVXZmhGU1ZubW5jdTNWMlNQREgzTXVYNVZYWnlmemJrV2xmOVJDcw0KcEI2MzZQRDRQUGlaaXVPVm9uR09IdThFNnlYZkVaVW5zYmZ0eTR2dTExMUVFSWZpSlRnNDBjVi9XaDdsTkJseA0KNTdDTVJvVUNnWUVBOHMvRzh0RlRuWVpkdjd5TkZWNjFqVXRNa3Mvc3ZnVWFYWU81NUZFZWw2MTFJMkZ2YWl4cQ0KbXkwTkVaaUJ4M09HcFRNVE84TDc5V0JwcUdaK0l0eEMwVlN4SGVMeXQ5SnFKcjFjOWRZb2FjUDRRcWE5aVJQcg0KNVBlYmd0ZmFzekQvUXVTdTV0RmROMTY1STZRYml1WFBQdGZxMDFEelZsQ20rZytJY04zR1dCc0NnWUVBdUh2VA0KeFFsVjJBdklNWXQ1b005QnpIZ2Q2YktGNjgyK1RSbmZ3bU95VVNxY1A3cG9NZ1cyZkpTdEZIc3ZLTUpEcmUxSA0KWm1uUUlZRGlBb0ZLYmNVbWdQNWlOQzg4TWhIYUZHQ1hBaHZneHc2SFU1Vms4NkM4OFdDM0owZDBMQk5nbTZRNA0Kc0lDUlZ5NnN5NHlHL0NVcFVQN1ZldWhGd3VrM01hMlVkdlUzVmhjQ2dZQlZzaE5MTzZuQkhOMFZnSnhpZ0d5Zg0KRTRaUkFtVlJvMGRzM2NMTDIvMXFGdVFTdXA2eDREODN5U3lsbXllaWx4bGNVS3huR1NnSHNDRmFOK0lvdDRnMQ0KalNoOW5jMkFKeGtqMXcxcURrMXhGcU1XRXZjdDNBUVRhWGhQTTVPU1RxYW9tMEZIWVhqK3c4V2YySm1INmhlOA0KM0VPYWxTVnN2MFpQVnhBV2xZOGRKUUtCZ0VRRi9KYnBrMHFmUllqbk9jak93eDlHcHhqMXA2WEQ3a2gxb3VrRg0KWThuRDRXc3FLNk5PTWZTTHlhb0VwZVhzZzVJTkxNZVplcEh2K09ZZGtEa2JlZEFVZkZkcmwxR0svWk9IN2dacw0KQ3h5NndiRlRJNjhsZEtXNEdMQ1dDMEw1UGlVRmo1V2RRbm9ZRHNUYkl5YXorU0VSWmR2MDYwd3NQQnJJT3pjRg0Kd2dxdkFvR0JBTUtRNVo3bWROcE9EZGlRd1RPbkpqSm5jdVlkNGFkeHBZbGY2dldxakFNRmxleGN3ZHVhTGw2OA0KOWJlRkM5OHU5TkhUczcwZll2UHJTNVBhZklua1REejM2ZDA3bUNHWmM1ZXlIejFSdTBoRVNiWmxmVHlTcHJiRQ0KaXYzK0hqVTZVbDhtbmwyYzBmWi9xREdBZXRWUnltV0lMbDIvVDgxODhBblJRMkNLQlJBag0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
  labels:
    app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  template:
    metadata:
      labels:
        app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
      containers:
        - name: server
          image: ghcr.io/defenseunicorns/pepr/controller:v0.13.0
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - 8fadc724f5a8e77989b502dbb21fe075ba9455d8bfee69d6d5deb1ddc9a78b9f
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          ports:
            - containerPort: 3000
          env:
            - name: PEPR_PRETTY_LOG
              value: 'false'
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: api-token
              mountPath: /app/api-token
              readOnly: true
            - name: module
              mountPath: /app/load
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-tls
        - name: api-token
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-api-token
        - name: module
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-module
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
spec:
  selector:
    app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-module
  namespace: pepr-system
type: Opaque
data:
  module-8fadc724f5a8e77989b502dbb21fe075ba9455d8bfee69d6d5deb1ddc9a78b9f.js.gz: >-
    H4sIAAAAAAAAE41WbZPbNBD+zq9QBXO1qawmkym0zviOTgpMoW/Ta+kMN2FOttaOGkcyknwhpP7vrOwkpG0O+iGOLO1qd59nX3wjLKmzl/l7KDyXUCoNr6xpwPrN9AbPZBZpZuLsvMZ/qsUKKNveiLqF1LDC6FJVrRV5DemdURf3KovMwp+tshDRBhpLh9082wbtlMJfYtXUkKwhXxizpOwGrFNGp3TER3xMmQRXWNX4fo+yJWzWxkqXXg3XMbp86PDZmFoVmwR0hT6HdzxMVka2dXhzULRW+Q2ds0HCpVttJNo/z8YP0dCIdiyopLe51bZKprTIH3z3aAJlIseTInlQwjjJHwiZFA+/H5Xy0XicT3LKjP7RWmNTqiptLNoX9Vps3NP+bbDgGlGgE1dzVosc6rDqOjZEir7R5UQmDnzb0DSsSVG3zgMSADV4IH10Em7I2Rk5Pi4siOPjJFlOXCJsRe4muJG31Q8OLEKcju5ixBIa0BJ0oQIgffz0D0R9EvDoeqLESfqaTMOaCD4TjchVjchGtwH3EX+PiVPhmOzESHG4gHhD3MKsSfjttB1BrpdkrfyC/C5sSRC1pagAYWhqs1mB9o5Tdgwo/Rvl6LyL2fbdAnRadlkzLSPBBb8EhMfH/Kmb9TDJl/ZtI8Miwk39Yn9LNNwR83do91mgB2MfDCeD4UTp0qDA89ajeqSz8y3SQkym+WuxZsAsc9md8dTbzdZmwps8Mhwtif4Rh8NRVwhfLPD46KQLCpD9cvnyBW+EdRDZeJCLfLwV/JmpOITUimgpVA0ygNYLEr8A4voA/70uJfSej6e411rdlagWvEQ/SwIXfAgF5MysGqMDlBcXV/PYc4dBtS7LMvqkF1G6omdn0WC+T6Lo+g2aK/aK5Jut54GEjii34waVrmMG/CD0bkfpBb/yF730HJfUg/OHZMEdk/cJKn8GDVaErEFHgFeH14sv8mMhHBE10iw3uJZE7FMKMw97AXJOEA+iPCcvjN9tos9EaINQWn4dp9EJ7z98OLWbbbuTsV4N7syz7cdx7rvMR5tswD2lr1utA+bscyzSYySwYSwxr1bgRU95uJMNFuM4ngYG74wujtIry70RUZ9dzls0ocpNhLLpscxnx9jHhdvogpStLoJdsuyHwFashfKkisajeBoSC3ZNARsy/7XNYdbPgynw2gj5kzWrJ1CKtvbRIG6R1pVYwuNGzWqFqEWD6gyb5G9j3I37+ulTNosGY5YHSg+VKoeSDrNoKNmY50Zu2GqoOX9cc+q4rFYxKzJ1gjBzIimnxS1pqY7IwAIp9pVDL9uiAJAgKTtt5FMTWREz/z9EqThmexSa0BNuhYF5dmOUJKP//NsuEEoctjhtkCmPDiZvNg3gwBFNg8O0D+s+2scWV6kiWYHFBthbvvfeGY0TYt+cXLwdmgw57lHXb3X4FAg9qu37bN+k9i18aFYp1uwncbq4w87huk5GS5zcNUDzWMvZQugKLnuAcQgdcrGK9MF4SD/8XFkpZNhk5zg/36gVmNZHhulvxzCJY7y02l2KtwSFBX+Fc+15/6UQ5eyqmcfTr+7f/5o409oCniMY6Njb18+yfqp+yRcAf+8ws5uv/gFbnkWCTgkAAA==
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
webhooks:
  - name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b.pepr.dev
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlNekE0TXpBeE5qRTBOVFJhRncweU5EQTRNekF4TmpFME5UUmFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDc3piNXBuMVV1WXV6WVRuT1ZDM0lSDQpKcDJxMXZ2em5zVEJ0cVJXK01DQXVyWUtjQnJuZml6TGVDMlFEQUg3cFAxc2R0Ymp5cENtUjhKQzJHUVNuR3hmDQpwVEJtMW5Mb2tXRTR3MklwOGtlL0ZDNnV0M1Vxc1RwQ2ZZOWdyd3JieHBnWVFJcFVMS21wbXY4WlJWdUY4NDdSDQpjWFNiVllFMGhNNnJ2a0thcmR5cmEvWmJwczFaNlRzakpMSFJzVUtJS3g4MFdEWGRWamM4SEJYUHpkMjk1dFFqDQp2d1FXWmFKV3VIR250cWgwRUgxMDlUNmJ3Tkk2SEx6Ynd2OXVnRitLaDZmMHBIY21BQ0Uyd1M5alpOUnVWamhXDQpYVHJ5dXZNeFFKNUM2b3lrME92OENERG11b1J3UW1DcE85UmVPQXNPbzZVNmVkK2JOZDFXOC9udzhGZTRteXRGDQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQ09KbEFjNmxGMVZxalk1Sk5hM2UrREpaNE5rMHdudVE3M0VodU82R3RoRys4bjVNRENqcDYyDQpQMXBDcGVqdXcyekF3clFKOUJIVlVRQVRtVVFobzQ2Wkx5bnhxN0I0azVrZHptbW8rSC9seVVnT0FSMXlmTnVpDQpabDJmZHF6VWVnam5NZy9EcDBacDU5d1N4Y1FzU1J1WWp6eG5ubTBJeTRQQkM0TExYVm9jdUFSRkRiRVBNZ0p1DQp2bUxsY2JHd2FOMVo0NFdoY2s1eW0zQ0YweGxldmFXY3EvalJTNGwvM2VWbDdmcVV6bjJKTVMzWkR2TU8yWmxLDQpyMWFDOUZ0bzRWUFZLSlp3QktsQmlVZ0pZaFVIWXphYVB2aTN4VUdoeFBUWjdJZjlBczhFaVFVV0poLzVwUzlEDQpkY2dJQktzU3ZCMkVZZUU1Z3U0UnBzU2t0RFdoWUQxcA0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
        namespace: pepr-system
        path: >-
          /mutate/c8a9f921ada875d1166e13b7875c2929914c96243cc204e8017f383c7bcb2e3b
    failurePolicy: Ignore
    matchPolicy: Equivalent
    timeoutSeconds: 10
    namespaceSelector:
      matchExpressions:
        - key: pepr.dev
          operator: NotIn
          values:
            - ignore
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    objectSelector:
      matchExpressions:
        - key: pepr.dev
          operator: NotIn
          values:
            - ignore
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - secrets
    sideEffects: None
