apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: podinfo
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/podinfo-6.0.0.tgz
---
# See https://github.com/stefanprodan/podinfo for docs on this example demployment
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-ssl-redirect@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 9898
