apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: webserver
  labels:
    domain: ###ZARF_VAR_DOMAIN###
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.name }}
    # domain: ###ZARF_VAR_DOMAIN###
  name: {{ .Values.name }}
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: docker.io/cmwylie19/hello-zarf
        name: {{ .Values.name }}
        command: ["./hello-zarf"]
        ports:
        - name: http
          containerPort: 8081
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.name }}
    domain: ###ZARF_VAR_DOMAIN###
  name: {{ .Values.name }}
  namespace: webserver
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: {{ .Values.name }}
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Values.name }}
    domain: ###ZARF_VAR_DOMAIN###
  name: {{ .Values.name }}
  namespace: webserver
spec:
  containers:
  - image: nginx
    name: {{ .Values.name }}
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
