apiVersion: v1
kind: Service
metadata:
  name: zarf-connect-logging
  labels:
    # Enables "zarf connect logging"
    zarf.dev/connect-name: logging    
  annotations:
    zarf.dev/connect-description: "Connect to the Zarf Logging Service (Grafana)"
spec:
  ports:
  - port: 3000
