apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/postgres-operator-1.7.0.tgz
  targetNamespace: postgres-operator
  # https://github.com/zalando/postgres-operator/blob/v1.7.0/charts/postgres-operator/values.yaml
  valuesContent: |-
#    image:
#      Eventually we'll need this to come from Iron Bank
#      registry: registry1.dso.mil
#      repository: ??
#      tag: ??
#    configGeneral:
#      docker_image: registry1.dso.mil/.../spilo-13:2.1-p1
    configPostgresPodResources:
      default_cpu_request: "100m"
      default_memory_request: "100Mi"
      default_cpu_limit: "500m"
      default_memory_limit: "500Mi"
      min_cpu_limit: "250m"
      min_memory_limit: "250Mi"
#    configLogicalBackup:
#      logical_backup_docker_image: "registry1.dso.mil/.../logical-backup:v1.7.0"
#      logical_backup_s3_endpoint: ""
#      logical_backup_s3_access_key_id: ""
#      logical_backup_s3_secret_access_key : ""
#      logical_backup_schedule: "30 00 * * *"
    configConnectionPooler:
#      connection_pooler_image: "registry1.dso.mil/.../pgbouncer:master-18"
      connection_pooler_default_cpu_request: "100m"
      connection_pooler_default_cpu_limit: "500m"
      connection_pooler_default_memory_request: "100Mi"
      connection_pooler_default_memory_limit: "100Mi"
    resources:
      requests:
        cpu: "100m"
        memory: "250Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
