apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pgadmin4
  namespace: postgres-operator
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/pgadmin4-1.7.2.tgz
  targetNamespace: postgres-operator
  # https://github.com/rowanruseler/helm-charts/blob/master/charts/pgadmin4/values.yaml
  valuesContent: |-
    # image:
      # registry: registry1.dso.mil
      # repository: ??
      # tag: ??
    imagePullSecrets:
      - name: private-registry
    serviceAccount:
      create: true
    persistentVolume:
      size: 2Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
      email: "zarf@example.local"
      password: "###ZARF_SECRET###"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-ingressroute
  namespace: postgres-operator
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pgadmin.localhost`)
      kind: Rule
      services:
        - name: pgadmin4
          port: 80
