apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/postgres-operator-1.7.0.tgz
  targetNamespace: postgres-operator
  # https://github.com/zalando/postgres-operator/blob/v1.7.0/charts/postgres-operator/values.yaml
  valuesContent: |-
    # image:
      # Eventually we'll need this to come from Iron Bank
      # registry: registry1.dso.mil
      # repository: ??
      # tag: ??
    configGeneral:
      repair_period: 3m
      resync_period: 5m
      # docker_image: registry1.dso.mil/.../spilo-13:2.1-p1
    imagePullSecrets:
      - name: private-registry
    configTimeouts:
      # timeout when waiting for the Postgres pods to be deleted
      pod_deletion_wait_timeout: 3m
      # timeout when waiting for pod role and cluster labels
      pod_label_wait_timeout: 3m
      # interval between consecutive attempts waiting for postgresql CRD to be created
      ready_wait_interval: 3s
      # timeout for the complete postgres CRD creation
      ready_wait_timeout: 30s
      # interval to wait between consecutive attempts to check for some K8s resources
      resource_check_interval: 3s
      # timeout when waiting for the presence of a certain K8s resource (e.g. Sts, PDB)
      resource_check_timeout: 3m
    configPostgresPodResources:
      default_cpu_request: "100m"
      default_memory_request: "100Mi"
      default_cpu_limit: "500m"
      default_memory_limit: "500Mi"
      min_cpu_limit: "250m"
      min_memory_limit: "250Mi"
    configAwsOrGcp:
      wal_s3_bucket: "postgres-operator-backups"
    configLogicalBackup:
      # logical_backup_docker_image: "registry1.dso.mil/.../logical-backup:v1.7.0"
      logical_backup_s3_endpoint: "http://minio.minio-operator.svc.cluster.local"
      logical_backup_s3_access_key_id: "minio"
      logical_backup_s3_bucket: "postgres-operator-backups"
      logical_backup_s3_secret_access_key : "minio123"
      logical_backup_s3_sse: ""
      logical_backup_schedule: "*/2 * * * *"
    configKubernetes:
      pod_environment_configmap: "postgres-operator/postgres-pod-config"
    configConnectionPooler:
      # connection_pooler_image: "registry1.dso.mil/.../pgbouncer:master-18"
      connection_pooler_default_cpu_request: "100m"
      connection_pooler_default_cpu_limit: "500m"
      connection_pooler_default_memory_request: "100Mi"
      connection_pooler_default_memory_limit: "100Mi"
    resources:
      requests:
        cpu: "100m"
        memory: "250Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
    podServiceAccount:
      name: "zalando-postgres-operator"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: postgres-operator
data:
  AWS_ENDPOINT: http://minio.minio-operator.svc.cluster.local
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  BACKUP_NUM_TO_RETAIN: "3"
  BACKUP_SCHEDULE: "*/2 * * * *"
  USE_WALG_BACKUP: "true"
  WALG_DISABLE_S3_SSE: "true"
  USE_WALG_RESTORE: "false"
  AWS_S3_FORCE_PATH_STYLE: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: zalando-postgres-operator
  namespace: postgres-operator
imagePullSecrets: 
    - name: private-registry