apiVersion: v1
kind: Service
metadata:
  name: minio-console-zarf-connect
  namespace: minio-operator
  annotations:
    zarf.dev/connect-description: "Launch the minio console, to get a JWT run:\n\n     kubectl -n minio-operator get secrets console-sa-secret -o jsonpath=\"{.data.token}\" | base64 --decode\n"
  labels:
    zarf.dev/connect-name: minio
spec:
  selector:
    app.kubernetes.io/instance: zarf-minio-operator-console
  ports:
    - name: http-console
      port: 9090
      protocol: TCP
      targetPort: 9090
