serviceAccount:
  create: true
persistentVolume:
  size: 2Gi
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
env:
  email: "admin@zarf.dev"
  password: "###ZARF_VAR_PGADMIN_PASSWORD###"
