name: Publish Injector Stage I

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: "Version tag"
        required: true
      branchName:
        description: "Branch to build the injector from"
        required: false
        default: "master"

jobs:
  build-injector:
    runs-on: ubuntu-latest
    steps:
      - name: "Dependency: Install cosign"
        uses: sigstore/cosign-installer@v2.5.0

      - name: "Dependency: Setup rust toolchain"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: "Dependency: Setup musl for x86_64"
        run: |
          rustup target add x86_64-unknown-linux-musl
          curl https://musl.cc/x86_64-linux-musl-cross.tgz | tar -xz
          echo "$PWD/x86_64-linux-musl-cross/bin" >> $GITHUB_PATH

      - name: "Dependency: Setup musl for aarch64"
        run: |
          rustup target add aarch64-unknown-linux-musl
          curl https://musl.cc/aarch64-linux-musl-cross.tgz | tar -xz
          echo "$PWD/aarch64-linux-musl-cross/bin" >> $GITHUB_PATH

      - name: "Checkout Repo"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: "Build Rust Binary for x86_64"
        run: |
          cargo build --target x86_64-unknown-linux-musl --release --manifest-path src/injector/stage1/Cargo.toml
          x86_64-linux-musl-strip src/injector/stage1/target/x86_64-unknown-linux-musl/release/zarf-injector

      - name: "Build Rust Binary for aarch64"
        run: |
          cargo build --target aarch64-unknown-linux-musl --release --manifest-path src/injector/stage1/Cargo.toml
          aarch64-linux-musl-strip src/injector/stage1/target/aarch64-unknown-linux-musl/release/zarf-injector

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Upload Binaries To DockerHub"
        run: |
          cosign upload blob -f src/injector/stage1/target/x86_64-unknown-linux-musl/release/zarf-injector defenseunicorns/zarf-injector:amd64-${{ github.event.inputs.versionTag }}
          cosign upload blob -f src/injector/stage1/target/aarch64-unknown-linux-musl/release/zarf-injector defenseunicorns/zarf-injector:arm64-${{ github.event.inputs.versionTag }}

      - name: "Sign the binaries"
        run: |
          cosign sign --key awskms:///${{ secrets.COSIGN_AWS_KMS_KEY }} -a release-engineer=https://github.com/${{ github.actor }} -a version=${{ github.event.inputs.versionTag }} defenseunicorns/zarf-injector:amd64-${{ github.event.inputs.versionTag }}
          cosign sign --key awskms:///${{ secrets.COSIGN_AWS_KMS_KEY }} -a release-engineer=https://github.com/${{ github.actor }} -a version=${{ github.event.inputs.versionTag }} defenseunicorns/zarf-injector:arm64-${{ github.event.inputs.versionTag }}
        env:
          COSIGN_EXPERIMENTAL: 1
          AWS_REGION: ${{ secrets.COSIGN_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COSIGN_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COSIGN_AWS_ACCESS_KEY }}
