name: cve-check
on: pull_request

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/golang

      - name: "Dependency: Install Grype"
        run: "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin"

      - name: "Check for CVEs in Dependencies"
        run: "make test-cves"

      - uses: ./.github/actions/logs
