name: cve-check
on:
  pull_request

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Dependency: Install Golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: "Dependency: Install Grype"
        run: "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin"

      - name: "Checkout Repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup caching"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Check for CVEs in Dependencies"
        run: "make test-cves"

      - name: "Save test debug logs"
        uses: actions/upload-artifact@v3
        with:
          name: debug-log
          path: /tmp/zarf-*.log
