name: DCO
on:
  merge_group:

permissions:
  contents: read

jobs:
  DCO:
    runs-on: ubuntu-latest
    steps:
      - run: echo "dummy DCO workflow (it won't run any check actually) to trigger by merge_group in order to enable merge queue"
