name: Enforce PR Labels
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]


jobs:
  enforce-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        BANNED_LABELS: "needs-docs,needs-tests,needs-adr"
