name: Test EKS Cluster
on:
  schedule:
   - cron: '0 7 * * * ' ## Every day at 0700 UTC

  workflow_dispatch: ## Give us the ability to run this manually

permissions:
  id-token: write
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-eks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Build binary and zarf packages
        uses: ./.github/actions/packages

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_NIGHTLY_ROLE }}
          aws-region: us-east-1

      - name: Build the eks package
        run: ./build/zarf package create packages/distros/eks -o build --confirm

      - name: Deploy the eks package
        run: ./build/zarf package deploy build/zarf-package-distro-eks-multi-0.0.2.tar.zst --components=deploy-eks-cluster --set=CLUSTER_NAME=zarf-nightly-eks-e2e-test,INSTANCE_TYPE=t3.medium --confirm

      # NOTE: We are copying the secret because part of the e2e process destroys the `zarf` namespace. We still want to test the remove-ability of the eks cluster via the package.
      - name: Copy the eks secret into a local file
        run: |
          rm -f eks.yaml
          ./build/zarf tools kubectl get secret -n zarf zarf-eks-yaml -o jsonpath='{.data.*}' | base64 -d > eks.yaml

      - name: Run tests
        run: make test-e2e ARCH=amd64

      # NOTE: We are copying the secret because part of the e2e process destroys the `zarf` namespace. We still want to test the remove-ability of the eks cluster via the package.
      - name: Re-create zarf namespace with eks.yaml secret
        run: |
          ./build/zarf tools kubectl create namespace zarf
          ./zarf tools kubectl create secret generic zarf-eks-yaml -n zarf --from-file=eks.yamls

      - name: Teardown the cluster
        if: always()
        run: ./build/zarf package deploy build/zarf-package-distro-eks-multi-0.0.2.tar.zst --components=teardown-eks-cluster --confirm

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
