name: Publish Zarf Packages on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  push-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Install GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build Things For Release
        run: make build-cli init-package
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GOV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GOV_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
      - name: Push Release Artifacts to S3 Bucket
        run: aws s3 cp build s3://zarf-public/release/${{ github.ref_name }} --region us-gov-west-1 --recursive
      - name: Create a Release For This Tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true    # Generates basic release notes that we can edit later
          body: |
            - [zarf](https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/${{ github.ref_name }}/zarf)
            - [zarf-mac-apple](https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/${{ github.ref_name }}zarf-mac-apple)
            - [zarf-mac-intel](https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/${{ github.ref_name }}zarf-mac-intel)
            - [zarf-init-amd64.tar.zst](https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/${{ github.ref_name }}/zarf-init-amd64.tar.zst)
            - [zarf-init-arm64.tar.zst](https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/${{ github.ref_name }}/zarf-init-arm64.tar.zst)
            - [zarf.sha256](https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/${{ github.ref_name }}/zarf.sha256)
          files: |
            build/zarf
            build/zarf-mac-intel
            build/zarf-mac-apple
            build/zarf-init-amd64.tar.zst
            build/zarf-init-arm64.tar.zst
            build/zarf.sha256
