name: Scan
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enforce:
    name: Validate Labels
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          BANNED_LABELS: "needs-docs,needs-tests,needs-adr,needs-git-sign-off"
