name: e2e-k3d
on:
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Install GoLang"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: "Checkout Repo"
        uses: actions/checkout@v2

      - name: "Setup caching"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-        

      - name: "Build CLI"
        run: make build-cli-linux

      - name: "Make Packages"
        run: make init-package package-example-game package-example-data-injection package-example-gitops-data package-example-compose

      - name: "Run Tests"
        # NOTE: This test run will create its own K3d cluster. A single cluster will be used throughout the test run.
        run: TESTDISTRO=k3d make test-e2e
