name: test-k3d
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: "Ensure workspace file ownership"
        run: chown -R $USER "$GITHUB_WORKSPACE"

      - name: "Install GoLang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Create a K3d cluster"
        run: k3d cluster delete && k3d cluster create

      - name: "Build CLI"
        run: make build-cli-linux-amd ARCH=amd64

      - name: "Make Packages"
        run: make init-package build-examples ARCH=amd64

      - name: "Run Tests"
        # NOTE: This test run will create its own K3d cluster. A single cluster will be used throughout the test run.
        run: make test-e2e ARCH=amd64

      - name: "Cleanup"
        run: make destroy
