name: test-k3s
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: "Install GoLang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Build CLI"
        run: make build-cli-linux-amd ARCH=amd64

      - name: "Make Packages"
        run: make init-package build-examples ARCH=amd64 AGENT_IMAGE=zarfdev/agent:${{ github.event.inputs.versionTag }}

      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: zarfdev
          password: ${{ secrets.ZARF_DEV_DOCKERHUB }}

      - name: "Copy binaries for packaging"
        run: cp build/zarf build/zarf-linux-amd64

      - name: "Build and Publish the Image"
        run: docker buildx build --push --platform linux/amd64 --tag zarfdev/agent:${{ github.event.inputs.versionTag }} .

      - name: "Run Tests"
        # NOTE: "PATH=$PATH" preserves the default user $PATH. This is needed to maintain the version of go installed
        #       in a previous step. This test run will use Zarf to create a K3s cluster, and a brand new cluster will be
        #       used for each test
        run: sudo env "PATH=$PATH" CI=true APPLIANCE_MODE=true make test-e2e ARCH=amd64

      - name: "Cleanup"
        run: sudo make destroy
