name: e2e-kind
on:
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Install GoLang"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: "Checkout Repo"
        uses: actions/checkout@v2
      - name: "Create k8s Kind Cluster"
        uses: helm/kind-action@v1.2.0
      - name: "Build CLI"
        run: make build-cli-linux
      - name: "Make Packages"
        run: make init-package package-example-game package-example-data-injection package-example-gitops-data package-example-compose
      - name: "Run Tests"
        run: make test-e2e
