# Attribution for a bunch of this goes to CloudPosse
# https://github.com/cloudposse/actions/blob/master/.github/workflows/test-command.yml

name: e2e
on:
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install GoLang
        uses: actions/setup-go@v2
        with: go-ersion: 1.16.x
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build CLI
        run: make build-cli init-package package-example-tiny-kafka

      - uses: engineerd/setup-kind@v0.5.0
        with:
          wait: 300s
          version: v0.11.1
          image: kindest/node:v1.20.7

      - name: Run Tests
        run: make
