name: e2e-kind
on:
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Install GoLang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Create k8s Kind Cluster"
        uses: helm/kind-action@v1.3.0

      - name: "Setup caching"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Build CLI binary & init-packages"
        run: make build-cli-linux-amd init-package ARCH=amd64

      - name: "Run Tests"
        # NOTE: We want to test providing a cluster to the test framework so this one creates its own KinD cluster
        #       rather than having the test suite do it. The K3d tests do a self-provisioned cluster and the K3s tests
        #       use Zarf to create the cluster. In this test a single cluster will be used throughout the test run.
        run: TESTDISTRO=provided make test-e2e
