name: test-kind
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "package.json"
      - "package-lock.json"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ../actions/golang
      - uses: ../actions/node

      - name: "Dependency: Kind Cluster Init"
        run: |
          kind delete cluster && kind create cluster
          kubectl scale deploy -n kube-system coredns --replicas=1

      - uses: ../actions/packages
        with:
          username: zarfdev
          password: ${{ secrets.ZARF_DEV_DOCKERHUB }}

      - run: make test-e2e ARCH=amd64

      - uses: ../actions/save-logs
