name: test-windows
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: Use GNU tar for Windows
        shell: cmd
        run: |
          echo "Adding GNU tar to PATH"
          echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      - uses: ./.github/actions/golang

      - name: "Build CLI"
        shell: pwsh
        run: make build-cli-windows-amd

      - name: "Make Packages"
        shell: pwsh
        run: make init-package build-examples ARCH=amd64

      - name: "Run Tests"
        shell: pwsh
        run: make test-e2e ARCH=amd64 -e SKIP_K8S=true
