name: e2e-kind
on:
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build CLI
        run: make build-cli-linux
      - name: Sign into Repo1
        run: ./build/zarf tools registry login registry1.dso.mil -u ${{ secrets.REGISTRY1_USERNAME_ZARF_ROBOT }} -p ${{ secrets.REGISTRY1_PASSWORD_ZARF_ROBOT }}
      - name: Make Packages
        run: make init-package

      - name: Run Tests
        run: TESTDISTRO=kind make test-e2e
