name: test-windows
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
        shell: cmd

      - uses: ../actions/golang
      - uses: ../actions/node

      - run: make build-cli-windows-amd
        shell: pwsh

      - run: make build-examples ARCH=amd64
        shell: pwsh

      - run: make test-e2e ARCH=amd64 -e SKIP_K8S=true
        shell: pwsh
