name: Test Big Bang extension
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "package.json"
      - "package-lock.json"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-bb-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Build Zarf binary
        uses: ./.github/actions/packages
        with:
          init-package: 'false'
          build-examples: 'false'

      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: Login to Iron Bank
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        if: ${{ env.IRONBANK_USERNAME != '' }}
        env:
          IRONBANK_USERNAME: ${{ secrets.IRONBANK_USERNAME }}
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.IRONBANK_USERNAME }}
          password: ${{ secrets.IRONBANK_PASSWORD }}

      - name: Build a registry1.dso.mil Zarf 'init' package
        run: make ib-init-package

      - name: Run tests
        if: ${{ env.IRONBANK_USERNAME != '' }}
        env:
          IRONBANK_USERNAME: ${{ secrets.IRONBANK_USERNAME }}
        run: "go test ./src/extensions/bigbang/test -failfast -v -timeout 30m"

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
