name: test-external
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: "Dependency: Install Golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: "Dependency: Install Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: "Dependency: K3d cluster init"
        run: k3d cluster delete && k3d cluster create

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Build CLI"
        run: make build-cli-linux-amd ARCH=amd64

      - name: "Zarf Agent: Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: zarfdev
          password: ${{ secrets.ZARF_DEV_DOCKERHUB }}

      - name: "Zarf Agent: Build and Publish the Image"
        run: |
          cp build/zarf build/zarf-linux-amd64
          docker buildx build --push --platform linux/amd64 --tag zarfdev/agent:$GITHUB_SHA .

      - name: "Make Init Package"
        run: make init-package AGENT_IMAGE=zarfdev/agent:$GITHUB_SHA

      - name: "Run Tests"
        # NOTE: This test run will create its own K3d cluster. A single cluster will be used throughout the test run.
        run: make test-external

      - name: "Cleanup"
        run: make destroy
