
name: zarf-schema-check
on:
  pull_request:
    paths:
      - "src/types/**"
      - "zarf.schema.json"
      - "docs/4-user-guide/1-the-zarf-cli/3-zarf-schema.md"
      - "src/cmd/**"
      - "docs/4-user-guide/1-the-zarf-cli/100-cli-commands/**"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Dependency: Install Golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Setup caching"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: "Regenerate Schema and Check that it Matches Generated"
        run: "make test-docs-and-schema"

      - name: "Save test debug logs"
        uses: actions/upload-artifact@v3
        with:
          name: debug-log
          path: /tmp/zarf-*.log
