name: zarf-schema-check
on:
  pull_request:
    paths:
      - "src/types/**"
      - "zarf.schema.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Dependency: Install Golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Setup caching"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Backup Repo Schema Version"
        run: 'cp zarf.schema.json zarf.schema.json.bak'

      - name: "Regenerate Schema"
        run: 'go run main.go internal config-schema > zarf.schema.json'

      - name: "Compare Schemas"
        run: 'cmp -s zarf.schema.json zarf.schema.json.bak'
