name: zarf-schema-check
on:
  pull_request:
    paths:
      - "src/types/**"
      - "zarf.schema.json"
      - "docs/4-user-guide/1-the-zarf-cli/3-zarf-schema.md"
      - "src/cmd/**"
      - "docs/4-user-guide/1-the-zarf-cli/100-cli-commands/**"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ../actions/golang
      - run: "make test-docs-and-schema"
      - uses: ../actions/save-logs
