persistence:
  storageClass: "###ZARF_STORAGE_CLASS###"
gitea:
  admin:
    username: "###ZARF_GIT_PUSH###"
    password: "###ZARF_GIT_AUTH_PUSH###"
    email: "zarf@localhost"
  config:
    APP_NAME: "Zarf Gitops Service"
    server:
      DISABLE_SSH: true
      OFFLINE_MODE: true
      ROOT_URL: http://zarf-gitea-http.zarf.svc.cluster.local:3000
    database:
      DB_TYPE: sqlite3
      # Note that the init script checks to see if the IP & port of the database service is accessible, so make sure you set those to something that resolves as successful (since sqlite uses files on disk setting the port & ip won't affect the running of gitea).
      HOST: zarf-docker-registry.zarf.svc.cluster.local:5000
    security:
      INSTALL_LOCK: true
    service:
      DISABLE_REGISTRATION: true
    repository:
      ENABLE_PUSH_CREATE_USER: true
      FORCE_PRIVATE: true
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "10"
    memory: "2Gi"

memcached:
  enabled: false

postgresql:
  enabled: false
